### ISSUE TITLE
Base tag not working with images

### ISSUE THREAD

**Issue by nhemenway** [SparkPost/heml#13]
When attempting to use the [base element](https://heml.io/docs/elements/meta#attributes-1) along with an `img`, I'm getting the following error: 

> (node:1612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Expected a string

I get this error whether or not my img src is relative or absolute.

Example:
```html
<heml>
  <head>
    <base href="http://via.placeholder.com" />
  </head>
  <body>
    <img src="/350x150" alt="my image" infer />
  </body>
</heml>
````

**Comment by avigoldman** [comment]
Oh good catch. Looks like there are a couple of bugs in this case.

1. base gets applied after the render so infer won't properly get applied
2. base is searching for both elements with `href` and `src` but only applying the base to the `href` attribute.

PR with the fix coming shortly!

**Comment by avigoldman** [comment]
I'd love to get your eyes on PR #16

For context:
- `$` is an instance of a cheerio dom (basically jquery on the server)
- `preRender` runs directly before all the elements are converted to HTML
- `postRender` runs directly after all the elements are converted to HTML

**Comment by nhemenway** [comment]
Makes sense. Thanks!
