### ISSUE TITLE
how  to use

### ISSUE THREAD

**Issue by nanxiaomo** [SparkPost/heml#14]

**Comment by nanxiaomo** [comment]
I am studying on this project, and Install the heml package globally.and create  HEML email in email.heml:
,then  use 

> ```heml build email.heml```

it make a file **email.html** .
i want to know how can I use  in the email ? to send others

**Comment by avigoldman** [comment]
Hey @nanxiaomo!

Once you have the HTML built you can use an email service provider (like [SparkPost](https://sparkpost.com/)) to send your email out.

**Comment by Leakermeli** [comment]
I am also interested in it

**Comment by avigoldman** [comment]
Hey 👋
1. For testing a really easy option is using [PutsMail](https://putsmail.com/). You can drop in the generated HTML and send off a test immediately.
2. To use in production sign up for a service like [SparkPost](https://www.sparkpost.com/signup-100k/?plan=free1&src=HEML) and follow the [New User Guide](https://www.sparkpost.com/docs/getting-started/getting-started-sparkpost/) to get started. 

There aren't great options for sending HTML emails from your personal email account, which is probably a good thing. Let me know if you have any other questions around this!
