### ISSUE TITLE
Changelog needed

### ISSUE THREAD

**Issue by avigoldman** [SparkPost/heml#17]
Gonna need to add a changelog and kick it off with the changes from #16 and #24

**Comment by yepher** [comment]
I like to stick a list of changes here when making a new relase:

**Comment by avigoldman** [comment]
So not creating a changelog? just documenting it in the latest release?

**Comment by aydrian** [comment]
In the past, I've maintained a CHANGELOG.MD and copied into the latest release, but I'm not sure you need to do both anymore. I know I check releases first. It's come a long way and it's a clean way to do it.

**Comment by avigoldman** [comment]
Makes my life easier 😜  Releases it is!
