### ISSUE TITLE
CLI doesn't resolve absolute paths

### ISSUE THREAD

**Issue by atipugin** [SparkPost/heml#18]
CLI treats absolute path as relative. Example:

```shell
$ heml build /Users/atipugin/Desktop/test-heml/test.heml
```

Fails with:

```shell
ENOENT: no such file or directory, open '/Users/atipugin/Desktop/test-heml/Users/atipugin/Desktop/test-heml/test.heml'
```

Version is `1.0.2-0`.

I think it should work with absolute paths too.

**Comment by atipugin** [comment]
https://github.com/SparkPost/heml/blob/26d988360f385e682d6f7c16a90fb45f0fe99562/packages/heml/src/bin/commands/build.js#L12

Maybe we could use `path.resolve` instead of joining with current workdir?

**Comment by avigoldman** [comment]
You're right, no reason not to use `path.resolve` instead of `path.join`

**Comment by avigoldman** [comment]
@atipugin can you take a quick look at PR #24?

**Comment by atipugin** [comment]
@avigoldman looks good!
