### ISSUE TITLE
Way to run via code/cli (without online editor)

### ISSUE THREAD

**Issue by ksmithut** [SparkPost/heml#2]
It wasn't clear from the website, but is there a supported way of running this offline? I'd like to be able to run this as a local build process rather than have to copy/paste my source code into the web browser every time I need to change something.

**Comment by jinchen93** [comment]
https://heml.io/docs/getting-started/usage has instructions on how to use the CLI / module.

**Comment by avigoldman** [comment]
@jinchen93 thanks for point that out 🎉 @ksmithut, do you think we should call that out on the home page? Or maybe on the editor?

**Comment by ksmithut** [comment]
I totally missed that. That’s my bad :) great project!
