### ISSUE TITLE
template imports

### ISSUE THREAD

**Issue by sdalezman** [SparkPost/heml#23]
Hey,

Just want to start off by saying heml has been super useful and easy to use. Took me about 30 minutes from installation to have my first full-featured email template. Keep up the awesome work (and came at the perfect time when I needed a new email template system).

As I've added another email template, it's becomes obvious that template imports would be super helpful (i.e. I share a footer, header, etc for my emails). So that I can reuse heml/styling between templates and make mass updates to my header without having to update each individual template - make the template writing a bit more dry.

Thanks!

**Comment by avigoldman** [comment]
Hey @sdalezman 👋 Correct me if I'm wrong, but does this cover the same issue in #6?

**Comment by sdalezman** [comment]
👋  avi - whoops totally missed that issue when I was searching. Yea it does

**Comment by avigoldman** [comment]
No worries! Its listed in a way that requires very specific knowledge! I'm gonna go ahead and close this issue.

**Comment by Anhoiemgoi** [comment]
https://www.facebook.com/dan.phamvan.50
