### ISSUE TITLE
Importing custom fonts

### ISSUE THREAD

**Issue by mattmanske** [SparkPost/heml#26]
I've been trying to import font files through various methods and can't seem to find anything that works correctly. I did come across this commit which seems related, but I didn't find any documentation around the `font` element or how to use it. https://github.com/SparkPost/heml/commit/3017190d7c7118864480e59968b45c6dd13a5b48

Any recommendations about how I would use custom fonts?

**Comment by avigoldman** [comment]
Hey @mattmanske 👋 You'll find the docs for the `<font />` element under the [Meta Elements section](https://heml.io/docs/elements/meta#font)

**Comment by mattmanske** [comment]
Indeed I will - whoops!
