### ISSUE TITLE
Table inside HEML

### ISSUE THREAD

**Issue by malexandre** [SparkPost/heml#40]
I don't see a particular reason to not give access to the table element directly. It would act kind of like HTML in markdown, where you could make a table yourself if HEML can't do a specific thing you want to.

For example, I want to use a table to make a sort of list with step. The min column width is too large for my "step" column, it adds too much spacing and makes the result weird. But having just a basic table would be enough in this case.

**Comment by avigoldman** [comment]
Hey @malexandre, you can use a table in HEML! This is totally valid HEML 😄 Let me know if you run into any issues with this.

```html
<heml>
  <head></head>
  <body>
    <table>
      <tr><td>my table</td></tr>
    </table>
  </body>
</heml>

**Comment by fritx** [comment]
@avigoldman `<td>` custom style gets lost in HEML
