### ISSUE TITLE
How to allow custom attributes

### ISSUE THREAD

**Issue by miix** [SparkPost/heml#57]
Hi,

First of all: love HEML!

Question: how to allow non-existent, custom attributes? For example:

`<img src="https://placeholdit.co//i/540x200" lp-edit="" lp-highres="" lp-label="Image">`

The attributes lp-edit, lp-highres and lp-label throws a validation error but i need them for internal usage.

Thanks in advance!

**Comment by miix** [comment]
Not possible?

**Comment by miix** [comment]
Apparently not ...

**Comment by mralexho** [comment]
@miix I was also looking to integrate this with MailChimp so I can insert some `mc:edit` merge tags but obviously this isn't supported. Perhaps someone will add a feature?

**Comment by jitendravyas** [comment]
I am also looking for this

**Comment by Kida007** [comment]
There is a workaround ( Hack by Jonny Burger) !!

1) leave markers.placeholders for custom attributes : 

```
<img src="https://placeholdit.co//i/540x200" lp-edit="{{ mylink }}" lp-highres="{{ mylink2 }}" lp-label="Image">
```


2) use readFileSync to read the heml file : 


```
import {readFileSync} from 'fs';

const template = readFileSync(
		path.join(__dirname, '..', 'path/to/file', 'myfile.heml'),
		'utf8'
	);
```


3) Replace Placeholders 

```

const filledTemplate = template
		.replace(/{{ mylink }}/g, link)
		.replace(/{{ mylink2 }}/g, link2)
```

Boom !
