### ISSUE TITLE
export to eml file?

### ISSUE THREAD

**Issue by karfau** [SparkPost/heml#7]
As far as I know lots of email clients support opening `.eml` files.

I don't know Mich about the file format, buy. Ssnce HEML already have at least parts of the metadata, It shouldn't be to hard to create such a file from a HEML file, right?

Would you see something like this as part of this repo, or prefer it as a separate project that uses HEML?

**Comment by avigoldman** [comment]
I am definitely not an expert on the `.eml` filetype. I'll see if we've got anyone at SparkPost who can provide more context on the value of it and the best practices for building an `.eml` file. My gut says that this should live as a separate project but if there is enough community interest, I'm open bundling it!

**Comment by avigoldman** [comment]
From the understanding I have now, it sounds like exporting to an `.eml` file will be perfect for the plaintext renderer. Thanks for bringing this up!

I'm gonna close this issue and open a new one around the plaintext renderer so we can move forward on this 👍
